#!/bin/sh

start() {
	echo "attach bt on ttyS4"
	rtk_hciattach -s 115200 ttyS4 rtk_h5
	su
}

stop() {
	echo "no impl"
}

case "$1" in
  start)
	start
        ;;
  stop)
	stop
        ;;
  restart|reload)
        stop
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
